import { NextRequest, NextResponse } from "next/server";
import {
  addTracksToPlaylist,
  createPlaylist,
  getValidAccessToken,
  searchArtistImageUrl,
  setPlaylistCoverImage,
  SpotifyApiError,
} from "@/lib/spotify";
import { buildPlaylistCoverImage } from "@/lib/playlistCover";
import { getTopTracks } from "@/lib/plays";

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json().catch(() => ({}))) as {
      year?: number;
      artist?: string;
      limit?: number;
    };
    const year = body.year;
    const artist = body.artist;
    const limit = Math.min(Math.max(body.limit ?? 500, 1), 500);

    const accessToken = await getValidAccessToken();

    const tracks = await getTopTracks({ year, artist }, limit);
    const uris = tracks.map((t) => t.uri).filter((uri): uri is string => !!uri);

    if (uris.length === 0) {
      return NextResponse.json({ ok: false, error: "No tracks to add" }, { status: 400 });
    }

    const name = artist
      ? `Best of ${artist}`
      : `Top ${uris.length} Tracks — ${year ?? "All Time"}`;
    const description = artist
      ? `Your ${uris.length} most-played ${artist} tracks, generated by Spotify Listening History.`
      : `Your top ${uris.length} most-played tracks (${year ?? "All Time"}), generated by Spotify Listening History.`;
    const playlist = await createPlaylist(accessToken, name, description);
    await addTracksToPlaylist(accessToken, playlist.id, uris);

    // Cover art is a nice-to-have — never fail playlist creation over it,
    // but do tell the caller if it didn't happen.
    let coverWarning: string | undefined;
    const coverArtist = artist ?? tracks[0]?.artistName;
    if (coverArtist) {
      try {
        const imageUrl = await searchArtistImageUrl(accessToken, coverArtist);
        if (imageUrl) {
          const cover = await buildPlaylistCoverImage(imageUrl);
          await setPlaylistCoverImage(accessToken, playlist.id, cover);
        } else {
          coverWarning = `Couldn't find a Spotify photo for ${coverArtist}, so no cover was set.`;
        }
      } catch (err) {
        console.error("Failed to set playlist cover image:", err);
        if (err instanceof SpotifyApiError && err.insufficientScope) {
          coverWarning = "Couldn't set the cover image — reconnect Spotify to grant image-upload permission.";
        } else {
          coverWarning = "Couldn't set the cover image.";
        }
      }
    }

    return NextResponse.json({ ok: true, url: playlist.url, count: uris.length, coverWarning });
  } catch (err) {
    console.error("Playlist creation failed:", err);
    if (err instanceof SpotifyApiError && err.status === 403) {
      if (err.insufficientScope) {
        return NextResponse.json(
          { ok: false, error: "Missing playlist permission", needsReauth: true },
          { status: 403 },
        );
      }
      return NextResponse.json(
        {
          ok: false,
          error:
            "Spotify rejected this as Forbidden. Check that this account has Premium, is listed " +
            "under the app's Development Mode users at developer.spotify.com/dashboard, and that " +
            "you've reconnected Spotify since playlist scopes were added.",
          needsReauth: true,
        },
        { status: 403 },
      );
    }
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ ok: false, error: message }, { status: 500 });
  }
}
